
services:
  mysql:
    image: mysql:8.4
    container_name: autoplex-mysql
    restart: always
    networks:
      - public-caddy
    environment:
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      # - /home/thomasnie/mysql:/var/lib/mysql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  backend:
    image: registry.nielth.com/admin/autoplex-backend
    container_name: autoplex-backend
    env_file:
      - .env.production
    volumes:
      - /mnt/sdc/:/sdc:ro
    expose: 
      - 8080
    networks:
      - public-caddy
    restart: always
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: registry.nielth.com/admin/autoplex-frontend
    networks:
      - public-caddy
    depends_on:
      - backend
    env_file:
      - .env.production
    container_name: autoplex-frontend 
    restart: always
    expose:
      - 80

networks:
  public-caddy:
    external: true

volumes:
  mysql_data:
    name: mysql_data
    external: true
