---
services:

  go:
    build: ./backend
    container_name: backend-go
    expose: 
      - 8080
    restart: always

  node-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - go
    env_file:
      - .env
    container_name: node-prod
    restart: always
    ports:
      - 8085:80
      - 8086:443

  flaresolverr:
    image: 21hsmw/flaresolverr:nodriver
    container_name: flaresolverr
    expose:
      - 8191
    environment:
      - LOG_LEVEL=info
    restart: always

