services:
  flask-api:
    build: ./backend
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    container_name: flask-api
    restart: always

  node-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - flask-api
    env_file:
      - .env
    container_name: node-prod
    restart: always
    ports:
      - 8085:80
      - 8086:443
