version: "3.7"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=Europe/Oslo
      - WEBUI_PORT=8080
    #volumes:
    #  - /f/qbittorrent/config:/config
    #  - /f/plex/movies:/downloads/movies
    #  - /f/plex/tvseries:/downloads/tvseries
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
  web:
    build: ./app
    container_name: api
    volumes:
      - ./app/:/code
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 1337:443
    depends_on:
      - web

