version: "3"

services:
  flask-api:
    build: ./backend
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    container_name: flask-api
    volumes:
      - ./backend/api:/api
    restart: always

  node-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - flask-api
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot/:ro
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    container_name: node-prod
    restart: always
    ports:
      - 8085:80
      - 8086:443
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
