version: "3.7"
services:
  web:
    build: ./app
    container_name: api
    volumes:
      - ./app/:/code
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./devops/cert/:/etc/nginx/ssl/:ro
    ports:
      - 1337:443
      - 88:80
    depends_on:
      - web
      - web_exam
    restart: unless-stopped
