version: "3"

services:

  flask-api:
    build: ./backend
    environment:
      - QBT_USER=${QBT_USER}
      - QBT_PASS=${QBT_PASS}
      - JWT_SECRET=${JWT_SECRET}
    container_name: flask-api
    volumes:
      - ./backend/api:/api
    restart: always
  # node-dev:
  #   image: node:18-alpine
  #   container_name: node-dev
  #   working_dir: "/app"
  #   depends_on:
  #     - flask-api
  #   volumes:
  #     - ./frontend:/app
  #   restart: always
  #   command: sh -c "yarn && yarn start"

  node-prod:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - flask-api
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot/:ro
    container_name: node-prod
    restart: always
    ports:
      - 8085:80
      - 8086:443
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw