version: "3"
services:
  api:
    build: ./backend
    container_name: flask-api
    environment:
      - QBT_USER=${QBT_USER}
      - QBT_PASS=${QBT_PASS}
    volumes:
      - ./backend/api:/api
    ports:
      - 5000:5000
    restart: always
  torrent-api:
    build: ./torrent-api
    container_name: torrent-api
    ports:
      - 5050:8080
    restart: always
  app-dev:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: node-dev
    volumes:
      - ./frontend:/app
    restart: always
    ports:
      - 3000:3000
  # nginx:
  #   build: 
  #     context: ./frontend
  #     dockerfile: prod.Dockerfile
  #   container_name: app-prod
  #   ports:
  #     - 8080:80
  #   restart: always