---
services:
  flask-api:
    build: ./backend
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    command: flask --app api.py run --host=0.0.0.0 --reload --debugger
    ports:
      - 5050:5000
    volumes:
      - ./backend/api:/api
    restart: always

  flaresolverr:
    image: 21hsmw/flaresolverr:nodriver
    container_name: flaresolverr
    expose:
      - 8191
    environment:
      - LOG_LEVEL=info
    restart: always

