version: "3"

services:
  flask-api:
    build: ./backend
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    command: flask --app api.py run --host=0.0.0.0 --reload --debugger
    ports:
      - 5050:5000
    volumes:
      - ./backend/api:/api
    restart: always

  node-dev:
    image: node:18-alpine
    working_dir: "/app"
    depends_on:
      - flask-api
    volumes:
      - ./frontend:/app
    restart: always
    command: sh -c "yarn && yarn start"
    env_file:
      - .env
    ports:
      - 3000:3000
