version: "3.7"
services:
  web:
    build: ./app
    container_name: api
    volumes:
      - ./app/:/code
    restart: unless-stopped
    networks:
      vpcbr:
  nginx:
    build: ./nginx
    #image: nginx-build
    container_name: nginx
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 1337:443
      - 88:80
    depends_on:
      - web
    restart: unless-stopped
    networks:
      vpcbr:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  vpcbr:
