services:
  go:
    build: ./backend
    container_name: backend-go
    env_file:
      - .env.development
    volumes:
      - /tmp:/sdc:ro
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
